// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-L3rGClvlIB5RmtWhfpJoDQrdNo0sHTs',
    appId: '1:186651766354:web:b68296a357e01ccb00f98b',
    messagingSenderId: '186651766354',
    projectId: 'open-app-store-10x',
    authDomain: 'open-app-store-10x.firebaseapp.com',
    storageBucket: 'open-app-store-10x.appspot.com',
    measurementId: 'G-LT8Z6DSF4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMJL1niUjJcMLd3SGa7ld8qNYzn-qKte0',
    appId: '1:186651766354:android:eb89fb62ce20cf8300f98b',
    messagingSenderId: '186651766354',
    projectId: 'open-app-store-10x',
    storageBucket: 'open-app-store-10x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDYwZRhbDrDbvAwoQdv6gJqndcQbi9Mt8',
    appId: '1:186651766354:ios:80cfd7a678fee9e600f98b',
    messagingSenderId: '186651766354',
    projectId: 'open-app-store-10x',
    storageBucket: 'open-app-store-10x.appspot.com',
    iosClientId: '186651766354-u95jnq47jrckj558kq1hmgdef4ucbrsn.apps.googleusercontent.com',
    iosBundleId: 'com.omegaui.openAppStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDYwZRhbDrDbvAwoQdv6gJqndcQbi9Mt8',
    appId: '1:186651766354:ios:80cfd7a678fee9e600f98b',
    messagingSenderId: '186651766354',
    projectId: 'open-app-store-10x',
    storageBucket: 'open-app-store-10x.appspot.com',
    iosClientId: '186651766354-u95jnq47jrckj558kq1hmgdef4ucbrsn.apps.googleusercontent.com',
    iosBundleId: 'com.omegaui.openAppStore',
  );
}
